# Generated by Django 2.0 on 2021-08-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_checkbox1',
            field=models.BooleanField(default=False, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_checkbox2',
            field=models.BooleanField(default=False, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
