# Generated by Django 2.0 on 2021-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0002_auto_20210825_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_checkbox1',
            field=models.BooleanField(default=False, verbose_name='choose 1 as Profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_checkbox2',
            field=models.BooleanField(default=False, verbose_name='choose 2 as Profile picture'),
        ),
    ]
