# Generated by Django 2.0 on 2021-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0003_auto_20210825_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_checkbox1',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_checkbox2',
            field=models.BooleanField(default=False, verbose_name='Choose image 2 as profile picture, default profile picture is image 1'),
        ),
    ]
