# Generated by Django 2.0 on 2021-08-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0005_auto_20210825_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
